name: metadata
permissions:
  contents: read
on:
  workflow_dispatch:
  schedule:
    - cron: "24 5 1 * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8 # v2.1.3
        with:
          go-version: 1.19.x
      - name: Configure Go Environment
        run: |
          echo GOPATH=${{ runner.workspace }} >> $GITHUB_ENV
          echo ${{ runner.workspace }}/bin >> $GITHUB_PATH
      - name: Go Environment
        run: go env
      - name: Checkout code
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
        with:
          persist-credentials: false
      - name: Bootstrap
        run: ./script/bootstrap
      - name: Update Package Metadata
        run: ./script/metadata
      - name: Diff
        run: git diff
      - name: Generate
        run: ./script/generate
      - name: Diff
        run: git diff
      - name: Create Pull Request
        uses: ./.github/actions/create-pull-request
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          branch: auto-tests-thirdparty-update-metadata
          title: "tests/thirdparty: update package metadata"
          body: "Auto-generated update of third-party package metadata."
