name: stress

permissions:
  contents: read

on:
  schedule:
    - cron: '33 3 * * 6'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        GOFLAGS: -tags=stress
    steps:
    - name: Install Go
      uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8 # v2.1.3
      with:
        go-version: 1.18.x
    - name: Configure Go Environment
      run: |
        echo GOPATH=${{ runner.workspace }} >> $GITHUB_ENV
        echo ${{ runner.workspace }}/bin >> $GITHUB_PATH
    - name: Go Environment
      run: go env
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
      with:
        persist-credentials: false
    - name: Bootstrap
      run: ./script/bootstrap

    - name: Generate
      run: ./script/generate
    - name: Status
      run: git status

    - name: Build
      run: go build ./...
    - name: Test
      run: go test -bench . ./...
    - name: Coverage
      run: ./script/coverage

    - name: Upload Stress Unit Test Coverage
      uses: codecov/codecov-action@51d810878be5422784e86451c0e7c14e5860ec47 # v2.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: unittests.coverprofile
        flags: stress
