name: stress
permissions:
  contents: read
on:
  schedule:
    - cron: "33 3 * * 6"
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -tags=stress
    steps:
      - name: Install Go
        uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v3.0.0
        with:
          go-version: 1.19.x
          check-latest: true
      - name: Configure Go Environment
        run: |
          echo GOPATH=${{ runner.workspace }} >> $GITHUB_ENV
          echo ${{ runner.workspace }}/bin >> $GITHUB_PATH
      - name: Go Environment
        run: go env
      - name: Checkout code
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
        with:
          persist-credentials: false
      - name: Bootstrap
        run: ./script/bootstrap
      - name: Generate
        run: ./script/generate
      - name: Status
        run: git status
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -bench . ./...
      - name: Coverage
        run: ./script/coverage
      - name: Upload Stress Unit Test Coverage
        uses: codecov/codecov-action@51d810878be5422784e86451c0e7c14e5860ec47 # v2.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: unittests.coverprofile
          flags: stress
